# Generated by Django 5.2.7 on 2025-11-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.CharField(default='CO-301', max_length=100)),
                ('event_type', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
